### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by johnreynolds123** [Matttaylor8910/f3nearme#1]
From GA

[f3near.me.ga.txt](https://github.com/Matttaylor8910/f3nearme/files/9649829/f3near.me.ga.txt)

**Comment by Matttaylor8910** [comment]
Google analytics is already wired up via the FirestoreAnalyticsModule:
https://github.com/Matttaylor8910/f3nearme/commit/1c6fa6afb8e1889ec626be6f2898c14ca58c6aff

**Comment by johnreynolds123** [comment]
Saaaaweeeeet!
